// import Head from "next/head";
// import Image from "next/image";
// import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";

// const inter = Inter({ subsets: ["latin"] });

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>LAYOUTindex Assesment</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className="bg-blue-300">
//         <h2 className="text-green-500 font-bold-300">This is working</h2>
//       </main>
//     </>
//   );
// }

import React from "react";
import { useState, useEffect } from "react";
// import Layout from "../../components/Layout";
import { logIn, isAuth, authenticate, getCookie } from "../../actions/auth";
import Router from "next/router";
// import Message from "../../components/Message";
import Link from "next/link";
import Message from "components/Message";
import {
  FaFacebookF,
  FaLinkedinIn,
  FaGoogle,
  FaRegEnvelope,
} from "react-icons/fa";
import { MdLockOutline } from "react-icons/md";

const LogIn = () => {
  const [values, setValues] = useState({
    email: "",
    password: "",
    error: "",
    loading: false,
    message: "",
    showForm: true,
  });

  const [alert, setAlert] = useState({
    message: "",
    error: false,
    loading: false,
    success: false,
  });

  useEffect(() => {
    if (getCookie("token_user")) {
      Router.push(`/`);
    }
  }, []);

  const resetAlert = () => {
    setAlert({ message: "", error: false, loading: false, success: false });
  };

  const { email, password, error, loading, message, showForm } = values;

  const handleSubmit = async (e) => {
    e.preventDefault();
    setAlert({ ...alert, loading: true });
    setValues({ ...values, loading: true, error: false });
    const user = { email, password };

    await logIn(user)
      .then((data) => {
        // console.log(data);
        if (data.status && data.status == "success") {
          data.data.token = data.token;
          setAlert({
            ...alert,
            loading: false,
            message: data.message,
            error: false,
            success: true,
          });
          window.setTimeout(() => {
            setAlert({ ...alert, success: false, message: "" });
          }, 1500);

          // console.log(data);
          // console.log(data.error);
          authenticate(data.data, "user", () => {
            if (localStorage.getItem("user")) {
              Router.push(`/main`);
            }
          });
        } else {
          setAlert({
            ...alert,
            loading: false,
            message: data.message,
            error: true,
            success: false,
          });
        }
      })
      .catch((err) => {
        console.log(err);
        setAlert({
          ...alert,
          loading: false,
          message: data.message,
          error: true,
          success: false,
        });
      });
  };

  const handleChange = (name) => (e) => {
    e.preventDefault();
    setValues({ ...values, error: false, [name]: e.target.value });
  };
  return (
    <>
      {/* <Layout> */}
      {/* <!-- Login --> */}
      {alert.error && (
        <Message
          message={alert.message}
          // alert={"error"}
          resetAlert={resetAlert}
        />
      )}
      {alert.success && (
        <Message
          message={alert.message}
          // alert={"success"}
          resetAlert={resetAlert}
        />
      )}
      {alert.loading && (
        <Message
          message={"Loading...Please Waite..."}
          // alert={"loading"}
          resetAlert={resetAlert}
        />
      )}
      <div className="flex flex-row md:flex-col items-center justify-center min-h-screen py-2 bg-blue-100">
        <div className="flex flex-row md:flex-col items-center justify-center md:w-full flex-2 md:px-20 text-center">
          <div className="bg-blue rounded-2xl shadow-2xl md:flex md:w-2/3 md:max-w-4xl">
            <div className="md:w-3/5 p-5">
              <div className="md:py-10">
                <h2 className="text-3xl font-bold text-primary-500 mb-2">
                  Log In to Account
                </h2>
                <div className="border-2 w-10 border-primary-500 inline-block mb-2"></div>

                {/* <div className='flex justify-center my-2'>
                <a href='#' className='border-2 border-gray-200 rounded-full p-3 mx-1'>
                  <FaFacebookF className='text-sm' />
                </a>
                <a href='#' className='border-2 border-gray-200 rounded-full p-3 mx-1'>
                  <FaLinkedinIn className='text-sm' />
                </a>
                <a href='#' className='border-2 border-gray-200 rounded-full p-3 mx-1'>
                  <FaGoogle className='text-sm' />
                </a>
              </div>
              
              <p className='text-gray-400 my-3'>or use your email account</p>
               */}
                <div className="flex mt-10 flex-col items-center">
                  <div className="bg-gray-100 w-64 p-2 flex items-center mb-3">
                    <FaRegEnvelope className="text-gray-400 m-2" />
                    <input
                      type="email"
                      name="email"
                      value={email}
                      onChange={handleChange("email")}
                      placeholder="Email"
                      className="bg-gray-100 outline-none text-sm"
                    />
                  </div>
                  <div className="bg-gray-100 w-64 p-2 flex items-center mb-3">
                    <MdLockOutline className="text-gray-400 m-2" />
                    <input
                      type="password"
                      name="password"
                      value={password}
                      onChange={handleChange("password")}
                      placeholder="Password"
                      className="bg-gray-100 outline-none text-sm"
                    />
                  </div>

                  <button
                    onClick={handleSubmit}
                    className=" mt-5 border-2 border-primary-500 text-primary-500 rounded-full px-11 py-1 font-semibold hover:bg-primary-500 hover:text-blue"
                  >
                    LogIn
                  </button>
                </div>
              </div>
            </div>

            <div className="md:w-2/5 bg-primary-500 text-blue rounded-tr-2xl rounded-br-2xl md:py-36 md:px-16 pb-4 ">
              {/* <img
                src="/img/opd-logo.png"
                alt="logo"
                height={250}
                width={250}
                className="item-center item"
              /> */}
              <h2 className="item-center item font-bold text-2xl text-blue">
                LAYOUTindex_A
              </h2>
              <div className="border-2 w-10 border-blue inline-block mb-2"></div>
              <p className="mb-2 text-base">
                <b>Assesment</b>
              </p>
              <br />
              <p className="mb-2">Don't have an account?</p>
              <Link
                href={`/auth/SignUp`}
                className="border-2 border-blue rounded-full px-11 py-1 font-semibold hover:bg-blue hover:text-primary-500"
              >
                Sign up
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default LogIn;
